### PR TITLE
Returns a DataFrame if you call it from another python module

### PR DESCRIPTION
**Pull request by nazariyv**
All the additions explained in the commit message.

I made this because I will be primarily using it in other python modules and did not want to pipe all the time. Original logic is the same (except for the validation). I have removed that validation because the argparser would actually throw an exception if you were to not provide it with a positional argument.

I have updated the README.md file as well. Could not make the code render with the <li></li> HTML tags for some reason... So I just made the text cursive instead, feel free to change to bullet points if you can somehow make the code render with them. If you have any questions, let me know :) :+1:

### CODE REVIEW

**Comment by nazariyv** [comment]
Hmm.. I have added another commit with a processDataFrame method that for some reason is not showing up here..

**Comment by nazariyv** [comment]
The last commit should be #41d3043, after #c93d3c9. For some reason not showing up here, but does in my fork...

**Comment by jhogan4288** [comment]
Hi Nazariyv -- thanks for the PR.  I'm noticing a few things:
- looks like Windows line endings are in the new version -- doesn't run as-is as macOS.  Not sure how this is normally handled -- did you have to convert the line endings when you first downloaded it?
- permissions were reset to non-executable
- Readme instructions about using as a python module seems like they should be in their own section, below "usage" and "where" (which are logically linked to each other)
 - I intentionally used only standard python modules so installation & usage for non-technical folks would be as simple as possible (i.e. no add'l installation at all on macOS aside from downloading the script).  Do you think there's some way to do this while still incorporating your changes?

**Comment by nazariyv** [comment]
Hi James, thanks for the comment!

- I can try and do this on my Linux machine, hopefully that is equivalent to the macOS?

- Quite easy to fix on Linux once again with the chmod.

- Will fix it.

- That is true.. pandas is not part of a standard library. I was actually thinking about this yesterday, thought might be an issue. I am flying today, so I will have a lot of time in the airport to fix this issue too. There must be a way! Let's have this pull request here for now, but I will create a new one most likely.

Once again, thanks for the comment!

**Comment by jhogan4288** [comment]
Yes, macOS is Unix-based, so should work!

**Comment by nazariyv** [comment]
Same PR, should be good now. Let me know if it is not.

**Comment by nazariyv** [comment]
Maybe we should have both the DOS and the Unix version here, or would that complicate things too much? I was trying to run this new coinmarketcap_usd_history on Windows now and getting issues, which I suspect have to do with the line endings. And the reason I am using Windows in the first place, is because there is this library called xlwings, that is quite nice for excel spreadsheets, and my use case is calling coinmarketcap_usd_history from other python modules + xlwings to import the data into the spreadsheet. But perhaps this would complicate things a bit... After all, anyone can just run unix2dos to get the module with the CRLF line endings. Yeah, that is probably more convenient.

**Comment by nazariyv** [comment]
Another problem I've ran into. Perhaps worth adding the ability for users to specify start_date and end_date instead of the start year and end year and defaulting the month and date. I was not able to retrieve the bitcoin-cash (using the importing with the python module option), as it apparently downloads some strings and then tries to convert those into floats. But this is optional. I will fix the problem in my Windows script.

**Comment by jhogan4288** [comment]
Hey nazariyv, thanks, I think this is getting there.  A few more things before I'd want to merge:

* the arguments shouldn't be printed out when the program is run; this is essentially debugging info, and also makes it so that the output is no longer a CSV format, hindering redirection (i.e. there's a non-CSV header at the beginning)

* README file formatting appears to be off -- shows up as all one paragraph when I render it as markdown.  Have you tried rendering it in a Markdown editor?

* Just per general standard practices, command-line arguments shouldn't be mixed-case / case-sensitive unless there's a compelling reason -- I recommend going with --dataframe or something similar

Happy for the script to take specific start/end dates rather than years!  That would certainly be a worthwhile feature.

**Comment by nazariyv** [comment]
Hi James,

Thank you for the comments. I have addressed them, although the README.md file appears fine to me. What may be the issue for you?

**Comment by jhogan4288** [comment]
The last section is hard to read, just a blog long paragraph.  I'll format it a bit.  Thanks for the PR

**Pull request merged**
